<a href="https://colab.research.google.com/github/theclosedbook/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this Notebook Were going to cover some of the fundamentals concepts of tensors using TensorFlow

More Specifically we're going to cover:
* Introduction to Tensors

* Getting Information from Tensors

* Manipulating Tensors

* Tensors & Numpy

* Using @tf.function(a way to speedup your regular Python function)

* Using GPU's with TensorFlow (or TPU's)

* Exercise try yourself


# Intoduction To Tensors

In [ ]:
#Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#create tensors with tf.constant()
scalar = tf.constant(7 )
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix
matrix = tf.constant([[10,7],[10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[1.,2.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 1.,  2.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Lets create a tensor

tensor = tf.constant([[[1,2,3,],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

what we've created so far
* Scalar : a single number

* Vector: a number with direction (e.g. wind speed and direction)

* Matrix : a 2-dimensional array of numbers

* Tensor : an n-dimensional array of numbers (when n can be any number, a 0-dimenisonal tensor is a scalr, a 1-dimensional tensor is a vector)


### Creating tensors with `tf.Variable`

In [ ]:
#Create same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchaneable_tensor = tf.constant([10,7])

changeable_tensor,unchaneable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#lets try chnage one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
#How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchaneable_tensor[0].assign(7)
unchaneable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑 `Note-` Rarely in practice ypu will need to decide whether to uae `tf.constant`or `tf.Variable` to create tensors, as Tensorflow does this for you. However, if in doubt , use `tf.constant` and. change it later if needed.

### Creating Random Tensors
Random tensors are tensors of some arbitary size which contain random numbers

In [ ]:
#create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

#Are they equal
random_1,random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor




In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent dosent effect learning )

not_shuffled = tf.constant ([[10,7],
                             [3,4],
                             [1,2]])
# Shuffle our non-shuffled tesnor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled,seed =42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 1,  2]], dtype=int32)>

In [ ]:
print(tf.random.uniform([10,2]))

tf.Tensor(
[[0.11995816 0.15721154]
 [0.9557673  0.28248155]
 [0.66914964 0.37800717]
 [0.66728365 0.38468206]
 [0.4622568  0.38350403]
 [0.9850898  0.42398536]
 [0.7516346  0.54322493]
 [0.27399862 0.43945467]
 [0.14269269 0.1333201 ]
 [0.8676256  0.6502143 ]], shape=(10, 2), dtype=float32)


In [ ]:
print(tf.random.normal([5,5]))

tf.Tensor(
[[ 1.738186    0.31081358 -1.2912135   1.0937327  -0.2249081 ]
 [-0.61383665 -0.7209865   0.79639757 -0.4171397   0.12463818]
 [ 1.4515733  -0.52549464 -0.59219337  0.2393219   0.1699371 ]
 [-0.03140557  0.02500493  0.32056513  0.90571296 -0.93196625]
 [-0.8390773   1.3541503   0.29350403  0.2075503  -0.9129399 ]], shape=(5, 5), dtype=float32)


In [ ]:
random_3 = tf.random.Generator.from_seed(9)
random_3 = random_3.uniform(shape = (3,2))
random_4 = tf.random.Generator.from_seed(10)
random_4 = random_4.uniform(shape = (3,2))

random_3,random_4 , random_3==random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.8203654 , 0.70470357],
        [0.9578625 , 0.02297425],
        [0.93598676, 0.6513264 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.93598676, 0.6513264 ],
        [0.31663585, 0.00111556],
        [0.9212191 , 0.3822806 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(random_3,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.8203654 , 0.70470357],
       [0.9578625 , 0.02297425],
       [0.93598676, 0.6513264 ]], dtype=float32)>

### Other ways to make tensors

In [ ]:
#create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#create a tensor of all zeros
tf.zeros([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Trrn Numpy arrays into tenosrs
The main difference between Numpy arrays and TensorFlow tensors is that tenosrs can be run on a GPU

In [ ]:
#You can turn Numpy array into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A =tf.constant(numpy_A,shape = (4,3,2))
A

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [ ]:
A.ndim

3

###Getting Information from Tensors
When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of our tensors

print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions (rank):",rank_4_tensor.ndim)
print("Shape of the tensor:",rank_4_tensor.shape)
print("Element alonmg the 0 axis:",rank_4_tensor.shape[0])
print("Element along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor))
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of the tensor: (2, 3, 4, 5)
Element alonmg the 0 axis: 2
Element along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors
Tensors can be indexed just like Python lists

In [ ]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension from each index expect for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#Get the last item of each of the row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Add in extra dimension to our rank2 2tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Expand 0 axis
tf.expand_dims(rank_2_tensor,axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors ( Tensors Operations )

**Basic operation**
`+,-,*,/`

In [ ]:
tensor_1 = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[11, 12, 13],
        [14, 15, 16]],

       [[17, 18, 19],
        [20, 21, 22]],

       [[23, 24, 25],
        [26, 27, 28]]], dtype=int32)>

In [ ]:
tensor_2 = tf.constant([[2,3],[5,6]])
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [ ]:
tensor_3 = tensor_1 + tensor_2

In [ ]:
tensor_3


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 10],
       [ 8, 10]], dtype=int32)>

In [ ]:
tensor_4 = tf.expand_dims(tensor_3,axis = -1)
tensor_4


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[12],
        [10]],

       [[ 8],
        [10]]], dtype=int32)>

In [ ]:
tensor_5 = tensor_4 + tensor_3

In [ ]:
tensor_5

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[24, 22],
        [18, 20]],

       [[20, 18],
        [18, 20]]], dtype=int32)>

In [ ]:
tf.multiply(tensor_5,tensor_4)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[288, 264],
        [180, 200]],

       [[160, 144],
        [180, 200]]], dtype=int32)>

### Matrix Multiplication

In [ ]:
#Matrix multiplication in TensorFlow


In [ ]:
print(tensor)
tf.matmul(tensor_1,tensor_1)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Matrix multipliaction with python operator "@"

tensor_1 @ tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor_1.shape

TensorShape([2, 2])

In [ ]:
tensor.shape

TensorShape([3, 2, 3])

In [ ]:
#create a tensor (3,2)
X=tf.constant([[1,2],[3,4],[5,6]])
#Create another tensor
Y=tf.constant([[7,8],[9,10],[10,11]])


### The Dot Product
Matrix multiplication is also reffered to as the dot product.

You can perform matrix multiplication using:
`tf.matmul()`
`tf.tensordot()`

In [ ]:
#Perform the dot product on X and Y
tf.tensordot(tf.transpose(X),Y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 84,  93],
       [110, 122]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  32],
       [ 53,  67,  74],
       [ 83, 105, 116]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  28,  31],
       [ 61,  64,  71],
       [ 95, 100, 111]], dtype=int32)>

In [ ]:
#CHeck the values of Y , reshape Y and transpose Y

print("Normal Y")
print(Y,"\n")

print("Y reshaped to (2,3):")
print(tf.reshape(Y,shape=(2,3)),"\n")

print("Y transposed")
print(tf.transpose(Y))

Normal Y
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [10 11]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 10 11]], shape=(2, 3), dtype=int32) 

Y transposed
tf.Tensor(
[[ 7  9 10]
 [ 8 10 11]], shape=(2, 3), dtype=int32)


In [ ]:
 tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  32],
       [ 53,  67,  74],
       [ 83, 105, 116]], dtype=int32)>

Generallly when performing matrix multiplication on two tensors and omne of the axes doesnt line up, you will transpose (rather than reshape) one of the tenosr to get satisfy the matrix multiplication rule

### Changing the datatype of a tensor

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
#Create. new tensor with default datatype (float32)

B=tf.constant([1.9,7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.9, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
#Change from float32 to float16
D= tf.cast(B,dtype = tf.float16)
D,D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.9, 7.4], dtype=float16)>,
 tf.float16)

### Aggregating Tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
#Get the absolute values

D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

###Lets go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* get the mean of a tensor
* get the sum of a tensor

In [ ]:
#get the minimum of a tensor
D,D.shape
tf.reduce_min(D)
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [ ]:
#Create a new tensor
N = tf.constant(np.random.randint(0,100,size = 50))
N,N.shape,N.dtype

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([67, 68, 10, 21, 72, 85, 90, 60,  2, 91, 57, 46, 19, 96, 36, 40, 73,
        48, 79, 63, 85, 70, 82, 26, 40, 70, 93, 68,  1,  8, 91, 94, 49, 93,
        24, 55, 86, 13, 79, 33, 40, 18, 85, 83, 87, 45,  9, 24, 15, 25])>,
 TensorShape([50]),
 tf.int64)

In [ ]:
#Get the min of the new tensor
tf.reduce_min(N)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
#Get the max of the new tensor
tf.reduce_max(N)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
#get the mean of the new tensor
tf.reduce_mean(N)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [ ]:
#get the sum of the new tensor
tf.reduce_sum(N)

<tf.Tensor: shape=(), dtype=int64, numpy=2714>

In [ ]:
#get the variance of the new tensor
M = tf.cast(N,dtype = tf.float32)
M
tf.math.reduce_variance(M)

<tf.Tensor: shape=(), dtype=float32, numpy=871.56165>

In [ ]:
#get the standard deviation of the new tensor
tf.math.reduce_std(M)

<tf.Tensor: shape=(), dtype=float32, numpy=29.522223>

### Find positional maximum and minimum

In [ ]:
#create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#index on our the largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
#create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One hot encoding tensors

In [ ]:
#Create a list of indices
some_list = [0,1,2,3]
#one hot encode our list of indices
tf.one_hot(some_list,depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth = 4 , on_value ="Pussy", off_value = "Anal")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Pussy', b'Anal', b'Anal', b'Anal'],
       [b'Anal', b'Pussy', b'Anal', b'Anal'],
       [b'Anal', b'Anal', b'Pussy', b'Anal'],
       [b'Anal', b'Anal', b'Anal', b'Pussy']], dtype=object)>

### Squaring , log , Square Root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Find the log
tf.math.log(tf.cast(H,dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy
Tensorflow interacts beautifully with Numpy arrays

In [ ]:
#create a tensor directly from a Numpy array
J = tf.constant(np.array ([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#convert our tensors back to Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#Convert tensor J to a Numpy array
J.numpy(), (type(J.numpy()))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

#check datatypes of each

numpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)